version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1337
      POSTGRES_DB: skinscore
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d skinscore'"]
      interval: 10s
      timeout: 3s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    volumes:
      - ./frontend:/api
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./server:/api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
    - DB_HOST=postgres
    - DB_USER=postgres
    - DB_PASSWORD=1337
    - DB_NAME=skinscore
    - DB_PORT=5432
    healthcheck:
      test: ["CMD-SHELL", "echo 'hello'"]
      interval: 10s
      timeout: 3s
      retries: 3
